/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myApp;

import org.junit.Test;

import static org.junit.Assert.*;
import java.io.*;
public class AppTest {
    @Test
    public void test_readStringFromStdinValid() {
        ByteArrayInputStream in = new ByteArrayInputStream("Abc".getBytes());
        System.setIn(in);
        Console c = new Console();
        String firstName = c.readStringFromStdin("Enter prename:");
        assertEquals("Abc", firstName);
        assertNotEquals("123", firstName);
    }

    @Test
    public void test_readStringFromStdinInvalid() {
        System.setIn(new ByteArrayInputStream("123\nAbc\n".getBytes()));
        Console c = new Console();
        String firstName = c.readStringFromStdin("Enter prename:");
        assertEquals("Abc", firstName);
        assertNotEquals(378, firstName);
    }

    @Test
    public void test_readIntegerFromStdinValid() {
        ByteArrayInputStream in = new ByteArrayInputStream("123".getBytes());
        System.setIn(in);
        Console c = new Console();
        int x = c.readIntegerFromStdin("Enter number for x:");
        assertEquals(123, x);
        assertNotEquals(378, x);
    }

    @Test
    public void test_readIntegerFromStdinInvalid() {
        System.setIn(new ByteArrayInputStream("abc\n123\n".getBytes()));
        Console c = new Console();
        int x = c.readIntegerFromStdin("Enter number for x:");
        assertEquals(123, x);
        assertNotEquals(378, x);
    }
}
